-- =============================================
-- Author:		Jaryn Seidl
-- Create date: 
-- Description:	
-- =============================================
CREATE PROCEDURE [fact].[updateHsplit] 
	-- Add the parameters for the stored procedure here
--	@p1 int = 0, 
--	@p2 int = 0
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	Merge
		dbo.hSplit dest using hSplitStg src
		on (
			dest.row_date = src.row_date
			and dest.interval = src.interval
			and dest.acd = src.acd
			and dest.split = src.split
			and dest.vendorID = src.vendorID
		) When Matched Then Update Set
--			dest.i_stafftime = src.i_stafftime
			dest.i_availtime = src.i_availtime
			,dest.i_acdtime = src.i_acdtime
			,dest.i_acwtime = src.i_acwtime
			,dest.i_acwouttime = src.i_acwouttime
			,dest.i_acwintime = src.i_acwintime
			,dest.[i_auxtime] = src.[i_auxtime]
			,dest.[i_auxouttime] = src.[i_auxouttime]
			,dest.[i_auxintime] = src.[i_auxintime]
			,dest.[i_othertime] = src.[i_othertime]
--			,dest.[maxstaffed] = src.[maxstaffed]
			,dest.[acwincalls] = src.[acwincalls]
			,dest.[acwintime] = src.[acwintime]
			,dest.[auxincalls] = src.[auxincalls]
			,dest.[auxintime] = src.[auxintime]
			,dest.[acwoutcalls] = src.[acwoutcalls]
			,dest.[acwouttime] = src.[acwouttime]
--			,dest.[acwoutoffcalls] = src.[acwoutoffcalls]
--			,dest.[acwoutofftime] = src.[acwoutofftime]
--			,dest.[acwoutadjcalls] = src.[acwoutadjcalls]
			,dest.[auxoutcalls] = src.[auxoutcalls]
			,dest.[auxouttime] = src.[auxouttime]
--			,dest.[auxoutoffcalls] = src.[auxoutoffcalls]
--			,dest.[auxoutofftime] = src.[auxoutofftime]
--			,dest.[auxoutadjcalls] = src.[auxoutadjcalls]
--			,dest.[event1] = src.[event1]
--			,dest.[event2] = src.[event2]
--			,dest.[event3] = src.[event3]
--			,dest.[event4] = src.[event4]
--			,dest.[event5] = src.[event5]
--			,dest.[event6] = src.[event6]
--			,dest.[event7] = src.[event7]
--			,dest.[event8] = src.[event8]
--			,dest.[event9] = src.[event9]
--			,dest.[assists] = src.[assists]
--			,dest.[inflowcalls] = src.[inflowcalls]
			,dest.[acdcalls] = src.[acdcalls]
			,dest.[anstime] = src.[anstime]
			,dest.[acdtime] = src.[acdtime]
			,dest.[acwtime] = src.[acwtime]
--			,dest.[o_acdcalls] = src.[o_acdcalls]
--			,dest.[o_acdtime] = src.[o_acdtime]
--			,dest.[o_acwtime] = src.[o_acwtime]
--			,dest.[acdcalls1] = src.[acdcalls1]
--			,dest.[acdcalls2] = src.[acdcalls2]
--			,dest.[acdcalls3] = src.[acdcalls3]
--			,dest.[acdcalls4] = src.[acdcalls4]
--			,dest.[acdcalls5] = src.[acdcalls5]
--			,dest.[acdcalls6] = src.[acdcalls6]
--			,dest.[acdcalls7] = src.[acdcalls7]
--			,dest.[acdcalls8] = src.[acdcalls8]
--			,dest.[acdcalls9] = src.[acdcalls9]
--			,dest.[acdcalls10] = src.[acdcalls10]
--			,dest.[backupcalls] = src.[backupcalls]
			,dest.[holdcalls] = src.[holdcalls]
			,dest.[holdtime] = src.[holdtime]
			,dest.[holdabncalls] = src.[holdabncalls]
			,dest.[transferred] = src.[transferred]
			,dest.[conference] = src.[conference]
			,dest.[abncalls] = src.[abncalls]
			,dest.[abntime] = src.[abntime]
--			,dest.[abncalls1] = src.[abncalls1]
--			,dest.[abncalls2] = src.[abncalls2]
--			,dest.[abncalls3] = src.[abncalls3]
--			,dest.[abncalls4] = src.[abncalls4]
--			,dest.[abncalls5] = src.[abncalls5]
--			,dest.[abncalls6] = src.[abncalls6]
--			,dest.[abncalls7] = src.[abncalls7]
--			,dest.[abncalls8] = src.[abncalls8]
--			,dest.[abncalls9] = src.[abncalls9]
--			,dest.[abncalls10] = src.[abncalls10]
			,dest.[dequecalls] = src.[dequecalls]
--			,dest.[dequetime] = src.[dequetime]
			,dest.[busycalls] = src.[busycalls]
--			,dest.[busytime] = src.[busytime]
			,dest.[disccalls] = src.[disccalls]
--			,dest.[disctime] = src.[disctime]
			,dest.[outflowcalls] = src.[outflowcalls]
--			,dest.[outflowtime] = src.[outflowtime]
--			,dest.[interflowcalls] = src.[interflowcalls]
--			,dest.[lowcalls] = src.[lowcalls]
--			,dest.[medcalls] = src.[medcalls]
--			,dest.[highcalls] = src.[highcalls]
--			,dest.[topcalls] = src.[topcalls]
			,dest.[acceptable] = src.[acceptable]
--			,dest.[servicelevel] = src.[servicelevel]
--			,dest.[period1] = src.[period1]
--			,dest.[period2] = src.[period2]
--			,dest.[period3] = src.[period3]
--			,dest.[period4] = src.[period4]
--			,dest.[period5] = src.[period5]
--			,dest.[period6] = src.[period6]
--			,dest.[period7] = src.[period7]
--			,dest.[period8] = src.[period8]
--			,dest.[period9] = src.[period9]
--			,dest.[maxocwtime] = src.[maxocwtime]
--			,dest.[callsoffered] = src.[callsoffered]
--			,dest.[periodchg] = src.[periodchg]
--			,dest.[svclevelchg] = src.[svclevelchg]
			,dest.[i_ringtime] = src.[i_ringtime]
			,dest.[ringtime] = src.[ringtime]
			,dest.[ringcalls] = src.[ringcalls]
--			,dest.[abnringcalls] = src.[abnringcalls]
--			,dest.[o_abncalls] = src.[o_abncalls]
--			,dest.[o_othercalls] = src.[o_othercalls]
--			,dest.[da_acwincalls] = src.[da_acwincalls]
--			,dest.[da_acwintime] = src.[da_acwintime]
--			,dest.[da_acwocalls] = src.[da_acwocalls]
--			,dest.[da_acwotime] = src.[da_acwotime]
--			,dest.[noansredir] = src.[noansredir]
--			,dest.[incomplete] = src.[incomplete]
--			,dest.[acdauxoutcalls] = src.[acdauxoutcalls]
--			,dest.[i_acdaux_outtime] = src.[i_acdaux_outtime]
--			,dest.[i_acdauxintime] = src.[i_acdauxintime]
--			,dest.[i_acdothertime] = src.[i_acdothertime]
--			,dest.[phantomabns] = src.[phantomabns]
--			,dest.[othercalls] = src.[othercalls]
--			,dest.[othertime] = src.[othertime]
--			,dest.[slvlabns] = src.[slvlabns]
--			,dest.[slvloutflows] = src.[slvloutflows]
			,dest.[i_arrived] = src.[i_arrived]
--			,dest.[i_auxtime0] = src.[i_auxtime0]
--			,dest.[i_auxtime1] = src.[i_auxtime1]
--			,dest.[i_auxtime2] = src.[i_auxtime2]
--			,dest.[i_auxtime3] = src.[i_auxtime3]
--			,dest.[i_auxtime4] = src.[i_auxtime4]
--			,dest.[i_auxtime5] = src.[i_auxtime5]
--			,dest.[i_auxtime6] = src.[i_auxtime6]
--			,dest.[i_auxtime7] = src.[i_auxtime7]
--			,dest.[i_auxtime8] = src.[i_auxtime8]
--			,dest.[i_auxtime9] = src.[i_auxtime9]
--			,dest.[i_da_acdtime] = src.[i_da_acdtime]
--			,dest.[i_da_acwtime] = src.[i_da_acwtime]
--			,dest.[i_tavailtime] = src.[i_tavailtime]
--			,dest.[i_tauxtime] = src.[i_tauxtime]
--			,dest.[maxtop] = src.[maxtop]
--			,dest.[i_normtime] = src.[i_normtime]
--			,dest.[i_ol1time] = src.[i_ol1time]
--			,dest.[i_ol2time] = src.[i_ol2time]
--			,dest.[i_tothertime] = src.[i_tothertime]
--			,dest.[max_tot_percents] = src.[max_tot_percents]
--			,dest.[acdcalls_r1] = src.[acdcalls_r1]
--			,dest.[acdcalls_r2] = src.[acdcalls_r2]
--			,dest.[i_acdtime_r1] = src.[i_acdtime_r1]
--			,dest.[i_acdtime_r2] = src.[i_acdtime_r2]
--			,dest.[i_acwtime_r1] = src.[i_acwtime_r1]
--			,dest.[i_acwtime_r2] = src.[i_acwtime_r2]
--			,dest.[i_ringtime_r1] = src.[i_ringtime_r1]
--			,dest.[i_ringtime_r2] = src.[i_ringtime_r2]
--			,dest.[i_othertime_r1] = src.[i_othertime_r1]
--			,dest.[i_othertime_r2] = src.[i_othertime_r2]
--			,dest.[i_auxtime_r1] = src.[i_auxtime_r1]
--			,dest.[i_auxtime_r2] = src.[i_auxtime_r2]
--			,dest.[i_otherstbytime_r1] = src.[i_otherstbytime_r1]
--			,dest.[i_otherstbytime_r2] = src.[i_otherstbytime_r2]
--			,dest.[i_auxstbytime_r1] = src.[i_auxstbytime_r1]
--			,dest.[i_auxstbytime_r2] = src.[i_auxstbytime_r2]
/*			,dest.[i_behindtime] = src.[i_behindtime]
			,dest.[i_autoreservetime] = src.[i_autoreservetime]
			,dest.[targetpercent] = src.[targetpercent]
			,dest.[targetpctchg] = src.[targetpctchg]
			,dest.[targetseconds] = src.[targetseconds]
			,dest.[targetsecchg] = src.[targetsecchg]
			,dest.[targetacdcalls] = src.[targetacdcalls]
			,dest.[targetabns] = src.[targetabns]
			,dest.[targetoutflows] = src.[targetoutflows]
			,dest.[intrdeliveries] = src.[intrdeliveries]
			,dest.[agsurpdeliveries] = src.[agsurpdeliveries]
			,dest.[agsurpprefcalls] = src.[agsurpprefcalls]
			,dest.[agsurpnprefcalls] = src.[agsurpnprefcalls]
			,dest.[callsurpdeliveries] = src.[callsurpdeliveries]
			,dest.[i_auxtime10] = src.[i_auxtime10]
			,dest.[i_auxtime11] = src.[i_auxtime11]
			,dest.[i_auxtime12] = src.[i_auxtime12]
			,dest.[i_auxtime13] = src.[i_auxtime13]
			,dest.[i_auxtime14] = src.[i_auxtime14]
			,dest.[i_auxtime15] = src.[i_auxtime15]
			,dest.[i_auxtime16] = src.[i_auxtime16]
			,dest.[i_auxtime17] = src.[i_auxtime17]
			,dest.[i_auxtime18] = src.[i_auxtime18]
			,dest.[i_auxtime19] = src.[i_auxtime19]
			,dest.[i_auxtime20] = src.[i_auxtime20]
			,dest.[i_auxtime21] = src.[i_auxtime21]
			,dest.[i_auxtime22] = src.[i_auxtime22]
			,dest.[i_auxtime23] = src.[i_auxtime23]
			,dest.[i_auxtime24] = src.[i_auxtime24]
			,dest.[i_auxtime25] = src.[i_auxtime25]
			,dest.[i_auxtime26] = src.[i_auxtime26]
			,dest.[i_auxtime27] = src.[i_auxtime27]
			,dest.[i_auxtime28] = src.[i_auxtime28]
			,dest.[i_auxtime29] = src.[i_auxtime29]
			,dest.[i_auxtime30] = src.[i_auxtime30]
			,dest.[i_auxtime31] = src.[i_auxtime31]
			,dest.[i_auxtime32] = src.[i_auxtime32]
			,dest.[i_auxtime33] = src.[i_auxtime33]
			,dest.[i_auxtime34] = src.[i_auxtime34]
			,dest.[i_auxtime35] = src.[i_auxtime35]
			,dest.[i_auxtime36] = src.[i_auxtime36]
			,dest.[i_auxtime37] = src.[i_auxtime37]
			,dest.[i_auxtime38] = src.[i_auxtime38]
			,dest.[i_auxtime39] = src.[i_auxtime39]
			,dest.[i_auxtime40] = src.[i_auxtime40]
			,dest.[i_auxtime41] = src.[i_auxtime41]
			,dest.[i_auxtime42] = src.[i_auxtime42]
			,dest.[i_auxtime43] = src.[i_auxtime43]
			,dest.[i_auxtime44] = src.[i_auxtime44]
			,dest.[i_auxtime45] = src.[i_auxtime45]
			,dest.[i_auxtime46] = src.[i_auxtime46]
			,dest.[i_auxtime47] = src.[i_auxtime47]
			,dest.[i_auxtime48] = src.[i_auxtime48]
			,dest.[i_auxtime49] = src.[i_auxtime49]
			,dest.[i_auxtime50] = src.[i_auxtime50]
			,dest.[i_auxtime51] = src.[i_auxtime51]
			,dest.[i_auxtime52] = src.[i_auxtime52]
			,dest.[i_auxtime53] = src.[i_auxtime53]
			,dest.[i_auxtime54] = src.[i_auxtime54]
			,dest.[i_auxtime55] = src.[i_auxtime55]
			,dest.[i_auxtime56] = src.[i_auxtime56]
			,dest.[i_auxtime57] = src.[i_auxtime57]
			,dest.[i_auxtime58] = src.[i_auxtime58]
			,dest.[i_auxtime59] = src.[i_auxtime59]
			,dest.[i_auxtime60] = src.[i_auxtime60]
			,dest.[i_auxtime61] = src.[i_auxtime61]
			,dest.[i_auxtime62] = src.[i_auxtime62]
			,dest.[i_auxtime63] = src.[i_auxtime63]
			,dest.[i_auxtime64] = src.[i_auxtime64]
			,dest.[i_auxtime65] = src.[i_auxtime65]
			,dest.[i_auxtime66] = src.[i_auxtime66]
			,dest.[i_auxtime67] = src.[i_auxtime67]
			,dest.[i_auxtime68] = src.[i_auxtime68]
			,dest.[i_auxtime69] = src.[i_auxtime69]
			,dest.[i_auxtime70] = src.[i_auxtime70]
			,dest.[i_auxtime71] = src.[i_auxtime71]
			,dest.[i_auxtime72] = src.[i_auxtime72]
			,dest.[i_auxtime73] = src.[i_auxtime73]
			,dest.[i_auxtime74] = src.[i_auxtime74]
			,dest.[i_auxtime75] = src.[i_auxtime75]
			,dest.[i_auxtime76] = src.[i_auxtime76]
			,dest.[i_auxtime77] = src.[i_auxtime77]
			,dest.[i_auxtime78] = src.[i_auxtime78]
			,dest.[i_auxtime79] = src.[i_auxtime79]
			,dest.[i_auxtime80] = src.[i_auxtime80]
			,dest.[i_auxtime81] = src.[i_auxtime81]
			,dest.[i_auxtime82] = src.[i_auxtime82]
			,dest.[i_auxtime83] = src.[i_auxtime83]
			,dest.[i_auxtime84] = src.[i_auxtime84]
			,dest.[i_auxtime85] = src.[i_auxtime85]
			,dest.[i_auxtime86] = src.[i_auxtime86]
			,dest.[i_auxtime87] = src.[i_auxtime87]
			,dest.[i_auxtime88] = src.[i_auxtime88]
			,dest.[i_auxtime89] = src.[i_auxtime89]
			,dest.[i_auxtime90] = src.[i_auxtime90]
			,dest.[i_auxtime91] = src.[i_auxtime91]
			,dest.[i_auxtime92] = src.[i_auxtime92]
			,dest.[i_auxtime93] = src.[i_auxtime93]
			,dest.[i_auxtime94] = src.[i_auxtime94]
			,dest.[i_auxtime95] = src.[i_auxtime95]
			,dest.[i_auxtime96] = src.[i_auxtime96]
			,dest.[i_auxtime97] = src.[i_auxtime97]
			,dest.[i_auxtime98] = src.[i_auxtime98]
			,dest.[i_auxtime99] = src.[i_auxtime99]
			,dest.[icrpullcalls] = src.[icrpullcalls]
			,dest.[icrpulltime] = src.[icrpulltime]
			,dest.[icrpullringcalls] = src.[icrpullringcalls]
			,dest.[redirectcalls] = src.[redirectcalls]
			,dest.[CMS] = src.[CMS]*/
		When Not Matched Then Insert(
			[row_date]
			,[interval]
--			,[starttime_utc]
--			,[intrvl]
			,[acd]
			,[split]
			,[vendorID]
			,[monthNum]
			,[yearNum]
--			,[i_stafftime]*/
			,[i_availtime]
			,[i_acdtime]
			,[i_acwtime]
			,[i_acwouttime]
			,[i_acwintime]
			,[i_auxtime]
			,[i_auxouttime]
			,[i_auxintime]
			,[i_othertime]
--			,[maxstaffed]*/
			,[acwincalls]
			,[acwintime]
			,[auxincalls]
			,[auxintime]
			,[acwoutcalls]
			,[acwouttime]
--			,[acwoutoffcalls]*/
--			,[acwoutofftime]*/
--			,[acwoutadjcalls]*/
			,[auxoutcalls]
			,[auxouttime]
/*			,[auxoutoffcalls]
			,[auxoutofftime]
			,[auxoutadjcalls]
			,[event1]
			,[event2]
			,[event3]
			,[event4]
			,[event5]
			,[event6]
			,[event7]
			,[event8]
			,[event9]
			,[assists]
			,[inflowcalls]*/
			,[acdcalls]
			,[anstime]
			,[acdtime]
			,[acwtime]
/*			,[o_acdcalls]
			,[o_acdtime]
			,[o_acwtime]
			,[acdcalls1]
			,[acdcalls2]
			,[acdcalls3]
			,[acdcalls4]
			,[acdcalls5]
			,[acdcalls6]
			,[acdcalls7]
			,[acdcalls8]
			,[acdcalls9]
			,[acdcalls10]
			,[backupcalls]*/
			,[holdcalls]
			,[holdtime]
			,[holdabncalls]
			,[transferred]
			,[conference]
			,[abncalls]
			,[abntime]
/*			,[abncalls1]
			,[abncalls2]
			,[abncalls3]
			,[abncalls4]
			,[abncalls5]
			,[abncalls6]
			,[abncalls7]
			,[abncalls8]
			,[abncalls9]
			,[abncalls10]*/
			
			,[dequecalls]
--			,[dequetime]
			,[busycalls]
--			,[busytime]
			,[disccalls]
--			,[disctime]
			,[outflowcalls]
--			,[outflowtime]
			
/*			,[interflowcalls]
			,[lowcalls]
			,[medcalls]
			,[highcalls]
			,[topcalls]*/
			,[acceptable]
--			,[servicelevel]
			
/*			,[period1]
			,[period2]
			,[period3]
			,[period4]
			,[period5]
			,[period6]
			,[period7]
			,[period8]
			,[period9]
			
			,[maxocwtime]
			,[callsoffered]
			,[periodchg]
			,[svclevelchg]*/
			,[i_ringtime]
			,[ringtime]
			,[ringcalls]
--			,[abnringcalls]
			
/*			,[o_abncalls]
			,[o_othercalls]
			,[da_acwincalls]
			,[da_acwintime]
			,[da_acwocalls]
			,[da_acwotime]
			,[noansredir]
			,[incomplete]
			,[acdauxoutcalls]
			
			,[i_acdaux_outtime]
			,[i_acdauxintime]*/
			,[i_acdothertime]
/*			,[phantomabns]
			,[othercalls]
			,[othertime]
			,[slvlabns]
			,[slvloutflows]*/
			,[i_arrived]
			
/*			,[i_auxtime0]
			,[i_auxtime1]
			,[i_auxtime2]
			,[i_auxtime3]
			,[i_auxtime4]
			,[i_auxtime5]
			,[i_auxtime6]
			,[i_auxtime7]
			,[i_auxtime8]
			,[i_auxtime9]
			
			,[i_da_acdtime]
			,[i_da_acwtime]
			,[i_tavailtime]
			,[i_tauxtime]
			,[maxtop]
			,[i_normtime]
			,[i_ol1time]
			,[i_ol2time]
			,[i_tothertime]
			,[max_tot_percents]
			,[acdcalls_r1]
			,[acdcalls_r2]
			
			,[i_acdtime_r1]
			,[i_acdtime_r2]
			,[i_acwtime_r1]
			,[i_acwtime_r2]
			,[i_ringtime_r1]
			,[i_ringtime_r2]
			,[i_othertime_r1]
			,[i_othertime_r2]
			,[i_auxtime_r1]
			,[i_auxtime_r2]
			
			,[i_otherstbytime_r1]
			,[i_otherstbytime_r2]
			,[i_auxstbytime_r1]
			,[i_auxstbytime_r2]
			,[i_behindtime]
			,[i_autoreservetime]
			
			,[targetpercent]
			,[targetpctchg]
			,[targetseconds]
			,[targetsecchg]
			,[targetacdcalls]
			,[targetabns]
			,[targetoutflows]
			,[intrdeliveries]
			
			,[agsurpdeliveries]
			,[agsurpprefcalls]
			,[agsurpnprefcalls]
			,[callsurpdeliveries]
			
			,[i_auxtime10]
			,[i_auxtime11]
			,[i_auxtime12]
			,[i_auxtime13]
			,[i_auxtime14]
			,[i_auxtime15]
			,[i_auxtime16]
			,[i_auxtime17]
			,[i_auxtime18]
			,[i_auxtime19]
			
			,[i_auxtime20]
			,[i_auxtime21]
			,[i_auxtime22]
			,[i_auxtime23]
			,[i_auxtime24]
			,[i_auxtime25]
			,[i_auxtime26]
			,[i_auxtime27]
			,[i_auxtime28]
			,[i_auxtime29]
			
			,[i_auxtime30]
			,[i_auxtime31]
			,[i_auxtime32]
			,[i_auxtime33]
			,[i_auxtime34]
			,[i_auxtime35]
			,[i_auxtime36]
			,[i_auxtime37]
			,[i_auxtime38]
			,[i_auxtime39]
			
			,[i_auxtime40]
			,[i_auxtime41]
			,[i_auxtime42]
			,[i_auxtime43]
			,[i_auxtime44]
			,[i_auxtime45]
			,[i_auxtime46]
			,[i_auxtime47]
			,[i_auxtime48]
			,[i_auxtime49]
			
			,[i_auxtime50]
			,[i_auxtime51]
			,[i_auxtime52]
			,[i_auxtime53]
			,[i_auxtime54]
			,[i_auxtime55]
			,[i_auxtime56]
			,[i_auxtime57]
			,[i_auxtime58]
			,[i_auxtime59]
			
			,[i_auxtime60]
			,[i_auxtime61]
			,[i_auxtime62]
			,[i_auxtime63]
			,[i_auxtime64]
			,[i_auxtime65]
			,[i_auxtime66]
			,[i_auxtime67]
			,[i_auxtime68]
			,[i_auxtime69]
			
			,[i_auxtime70]
			,[i_auxtime71]
			,[i_auxtime72]
			,[i_auxtime73]
			,[i_auxtime74]
			,[i_auxtime75]
			,[i_auxtime76]
			,[i_auxtime77]
			,[i_auxtime78]
			,[i_auxtime79]
			
			,[i_auxtime80]
			,[i_auxtime81]
			,[i_auxtime82]
			,[i_auxtime83]
			,[i_auxtime84]
			,[i_auxtime85]
			,[i_auxtime86]
			,[i_auxtime87]
			,[i_auxtime88]
			,[i_auxtime89]
			
			,[i_auxtime90]
			,[i_auxtime91]
			,[i_auxtime92]
			,[i_auxtime93]
			,[i_auxtime94]
			,[i_auxtime95]
			,[i_auxtime96]
			,[i_auxtime97]
			,[i_auxtime98]
			,[i_auxtime99]
			
			,[icrpullcalls]
			,[icrpullringcalls]
			,[redirectcalls]
			,[CMS]*/
		)
		Values (
			src.[row_date]
			,src.[interval]
			,src.[acd]
--			,src.[starttime_utc]
--			,src.[intrvl]
			,src.[split]
			,src.[vendorID]
			,src.[monthNum]
			,src.[yearNum]
			
--			,src.[i_stafftime]
			,src.[i_availtime]
			,src.[i_acdtime]
			,src.[i_acwtime]
			,src.[i_acwouttime]
			,src.[i_acwintime]
			,src.[i_auxtime]
			,src.[i_auxouttime]
			,src.[i_auxintime]
			,src.[i_othertime]
			
--			,src.[maxstaffed]
			,src.[acwincalls]
			,src.[acwintime]
			,src.[auxincalls]
			,src.[auxintime]
			,src.[acwoutcalls]
			,src.[acwouttime]
--			,src.[acwoutoffcalls]
--			,src.[acwoutofftime]
--			,src.[acwoutadjcalls]
			
			,src.[auxoutcalls]
			,src.[auxouttime]
--			,src.[auxoutoffcalls]
--			,src.[auxoutofftime]
--			,src.[auxoutadjcalls]
--			,src.[event1]
--			,src.[event2]
--			,src.[event3]
--			,src.[event4]
--			,src.[event5]
--			,src.[event6]
--			,src.[event7]
--			,src.[event8]
--			,src.[event9]
			
--			,src.[assists]
--			,src.[inflowcalls]
			,src.[acdcalls]
			,src.[anstime]
			,src.[acdtime]
			,src.[acwtime]
--			,src.[o_acdcalls]
--			,src.[o_acdtime]
--			,src.[o_acwtime]
			
--			,src.[acdcalls1]
--			,src.[acdcalls2]
--			,src.[acdcalls3]
--			,src.[acdcalls4]
--			,src.[acdcalls5]
--			,src.[acdcalls6]
--			,src.[acdcalls7]
--			,src.[acdcalls8]
--			,src.[acdcalls9]
--			,src.[acdcalls10]
			
--			,src.[backupcalls]
			,src.[holdcalls]
			,src.[holdtime]
			,src.[holdabncalls]
			,src.[transferred]
			,src.[conference]
			,src.[abncalls]
			,src.[abntime]
			
--			,src.[abncalls1]
--			,src.[abncalls2]
--			,src.[abncalls3]
--			,src.[abncalls4]
--			,src.[abncalls5]
--			,src.[abncalls6]
--			,src.[abncalls7]
--			,src.[abncalls8]
--			,src.[abncalls9]
--			,src.[abncalls10]
			
			,src.[dequecalls]
--			,src.[dequetime]
			,src.[busycalls]
--			,src.[busytime]
			,src.[disccalls]
--			,src.[disctime]
			,src.[outflowcalls]
--			,src.[outflowtime]
			
--			,src.[interflowcalls]
--			,src.[lowcalls]
--			,src.[medcalls]
--			,src.[highcalls]
--			,src.[topcalls]
			,src.[acceptable]
--			,src.[servicelevel]
			
--			,src.[period1]
--			,src.[period2]
--			,src.[period3]
--			,src.[period4]
--			,src.[period5]
--			,src.[period6]
--			,src.[period7]
--			,src.[period8]
--			,src.[period9]
			
----			,src.[maxocwtime]
--			,src.[callsoffered]
--			,src.[periodchg]
--			,src.[svclevelchg]
			,src.[i_ringtime]
			,src.[ringtime]
			,src.[ringcalls]
--			,src.[abnringcalls]
			
--			,src.[o_abncalls]
--			,src.[o_othercalls]
--			,src.[da_acwincalls]
--			,src.[da_acwintime]
----			,src.[da_acwocalls]
----			,src.[da_acwotime]
--			,src.[noansredir]
--			,src.[incomplete]
--			,src.[acdauxoutcalls]
			
--			,src.[i_acdaux_outtime]
--			,src.[i_acdauxintime]
			,src.[i_acdothertime]
--			,src.[phantomabns]
--			,src.[othercalls]
--			,src.[othertime]
--			,src.[slvlabns]
--			,src.[slvloutflows]
			,src.[i_arrived]
			
/*			,src.[i_auxtime0]
			,src.[i_auxtime1]
			,src.[i_auxtime2]
			,src.[i_auxtime3]
			,src.[i_auxtime4]
			,src.[i_auxtime5]
			,src.[i_auxtime6]
			,src.[i_auxtime7]
			,src.[i_auxtime8]
			,src.[i_auxtime9]
			
			,src.[i_da_acdtime]
			,src.[i_da_acwtime]
			,src.[i_tavailtime]
			,src.[i_tauxtime]
			,src.[maxtop]
			,src.[i_normtime]
			,src.[i_ol1time]
			,src.[i_ol2time]
			,src.[i_tothertime]
			,src.[max_tot_percents]
			,src.[acdcalls_r1]
			,src.[acdcalls_r2]
			
			,src.[i_acdtime_r1]
			,src.[i_acdtime_r2]
			,src.[i_acwtime_r1]
			,src.[i_acwtime_r2]
			,src.[i_ringtime_r1]
			,src.[i_ringtime_r2]
			,src.[i_othertime_r1]
			,src.[i_othertime_r2]
			,src.[i_auxtime_r1]
			,src.[i_auxtime_r2]
			
			,src.[i_otherstbytime_r1]
			,src.[i_otherstbytime_r2]
			,src.[i_auxstbytime_r1]
			,src.[i_auxstbytime_r2]
			,src.[i_behindtime]
			,src.[i_autoreservetime]
			
			,src.[targetpercent]
			,src.[targetpctchg]
			,src.[targetseconds]
			,src.[targetsecchg]
			,src.[targetacdcalls]
			,src.[targetabns]
			,src.[targetoutflows]
			,src.[intrdeliveries]
			
			,src.[agsurpdeliveries]
			,src.[agsurpprefcalls]
			,src.[agsurpnprefcalls]
			,src.[callsurpdeliveries]
			
			,src.[i_auxtime10]
			,src.[i_auxtime11]
			,src.[i_auxtime12]
			,src.[i_auxtime13]
			,src.[i_auxtime14]
			,src.[i_auxtime15]
			,src.[i_auxtime16]
			,src.[i_auxtime17]
			,src.[i_auxtime18]
			,src.[i_auxtime19]
			
			,src.[i_auxtime20]
			,src.[i_auxtime21]
			,src.[i_auxtime22]
			,src.[i_auxtime23]
			,src.[i_auxtime24]
			,src.[i_auxtime25]
			,src.[i_auxtime26]
			,src.[i_auxtime27]
			,src.[i_auxtime28]
			,src.[i_auxtime29]
			
			,src.[i_auxtime30]
			,src.[i_auxtime31]
			,src.[i_auxtime32]
			,src.[i_auxtime33]
			,src.[i_auxtime34]
			,src.[i_auxtime35]
			,src.[i_auxtime36]
			,src.[i_auxtime37]
			,src.[i_auxtime38]
			,src.[i_auxtime39]
			
			,src.[i_auxtime40]
			,src.[i_auxtime41]
			,src.[i_auxtime42]
			,src.[i_auxtime43]
			,src.[i_auxtime44]
			,src.[i_auxtime45]
			,src.[i_auxtime46]
			,src.[i_auxtime47]
			,src.[i_auxtime48]
			,src.[i_auxtime49]
			
			,src.[i_auxtime50]
			,src.[i_auxtime51]
			,src.[i_auxtime52]
			,src.[i_auxtime53]
			,src.[i_auxtime54]
			,src.[i_auxtime55]
			,src.[i_auxtime56]
			,src.[i_auxtime57]
			,src.[i_auxtime58]
			,src.[i_auxtime59]
			
			,src.[i_auxtime60]
			,src.[i_auxtime61]
			,src.[i_auxtime62]
			,src.[i_auxtime63]
			,src.[i_auxtime64]
			,src.[i_auxtime65]
			,src.[i_auxtime66]
			,src.[i_auxtime67]
			,src.[i_auxtime68]
			,src.[i_auxtime69]
			
			,src.[i_auxtime70]
			,src.[i_auxtime71]
			,src.[i_auxtime72]
			,src.[i_auxtime73]
			,src.[i_auxtime74]
			,src.[i_auxtime75]
			,src.[i_auxtime76]
			,src.[i_auxtime77]
			,src.[i_auxtime78]
			,src.[i_auxtime79]
			
			,src.[i_auxtime80]
			,src.[i_auxtime81]
			,src.[i_auxtime82]
			,src.[i_auxtime83]
			,src.[i_auxtime84]
			,src.[i_auxtime85]
			,src.[i_auxtime86]
			,src.[i_auxtime87]
			,src.[i_auxtime88]
			,src.[i_auxtime89]
			
			,src.[i_auxtime90]
			,src.[i_auxtime91]
			,src.[i_auxtime92]
			,src.[i_auxtime93]
			,src.[i_auxtime94]
			,src.[i_auxtime95]
			,src.[i_auxtime96]
			,src.[i_auxtime97]
			,src.[i_auxtime98]
			,src.[i_auxtime99]
			
			,src.[icrpullcalls]
			,src.[icrpullringcalls]
			,src.[redirectcalls]
			,src.[CMS]*/
		);
END
