CREATE TABLE [dbo].[ACD_INST] (
    [ACD_INST_SK]      NUMERIC (15, 1) NOT NULL,
    [CODE]             NVARCHAR (30)   NOT NULL,
    [DESCR]            NVARCHAR (30)   NOT NULL,
    [ACD_STRM_ID]      NUMERIC (15, 1) NOT NULL,
    [ACD_SITE_ID]      NVARCHAR (20)   NOT NULL,
    [ACD_MDL_NAME]     NVARCHAR (10)   NOT NULL,
    [ACD_UNIT]         NUMERIC (15, 1) NOT NULL,
    [TIME_ZONE_SK]     NUMERIC (15, 1) NOT NULL,
    [AP_FRML_SET_SK]   NUMERIC (15, 1) NULL,
    [UPD_TCS_LOGIN_SK] NUMERIC (15, 1) NOT NULL,
    [UPD_TS]           DATETIME        NOT NULL,
    CONSTRAINT [PKACDINST] PRIMARY KEY CLUSTERED ([ACD_INST_SK] ASC) WITH (FILLFACTOR = 90)
);

