CREATE TABLE [dbo].[ACD_LOGIN_STG] (
    [ACD_LOGIN_ID] NVARCHAR (20)   NULL,
    [ACD_INST_SK]  NUMERIC (15, 1) NULL,
    [EMP_SK]       NUMERIC (15, 1) NULL,
    [ACD_GRP_ID]   NVARCHAR (128)  NULL,
    [acd]          SMALLINT        NULL
);

