CREATE TABLE [dbo].[EMP] (
    [EMP_SK]            NUMERIC (15, 1) NOT NULL,
    [ID]                NCHAR (10)      NOT NULL,
    [LAST_NAME]         NVARCHAR (30)   NOT NULL,
    [FIRST_NAME]        NVARCHAR (30)   NOT NULL,
    [EFF_HIRE_NOM_DATE] NUMERIC (15, 1) NOT NULL,
    [TERM_NOM_DATE]     NUMERIC (15, 1) NOT NULL,
    [ACTIVE_FLAG]       NCHAR (1)       NOT NULL,
    [SHORT_NAME]        NVARCHAR (30)   NOT NULL,
    [SORT_NAME]         NVARCHAR (60)   NOT NULL,
    [TIME_ZONE_SK]      NUMERIC (15, 1) NOT NULL,
    [SENIORITY]         NVARCHAR (12)   NULL,
    [EMAIL_ADR]         NVARCHAR (255)  NULL,
    [MEMO]              NVARCHAR (MAX)  NULL,
    [UPD_TCS_LOGIN_SK]  NUMERIC (15, 1) NOT NULL,
    [UPD_TS]            DATETIME        NOT NULL,
    [IM_USR_NAME]       NVARCHAR (255)  NULL,
    CONSTRAINT [PKEMP] PRIMARY KEY CLUSTERED ([EMP_SK] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_EMP_TIME_ZONE] FOREIGN KEY ([TIME_ZONE_SK]) REFERENCES [dbo].[TIME_ZONE] ([TIME_ZONE_SK])
);

