CREATE TABLE [dbo].[EMP_GRP_ASS] (
    [EMP_GRP_ASS_SK]  NUMERIC (15, 1) NOT NULL,
    [EMP_SK]          NUMERIC (15, 1) NOT NULL,
    [EMP_GRP_NODE_SK] NUMERIC (15, 1) NOT NULL,
    [START_NOM_DATE]  NUMERIC (15, 1) NOT NULL,
    [STOP_NOM_DATE]   NUMERIC (15, 1) NOT NULL,
    [LDR]             NCHAR (1)       NOT NULL,
    CONSTRAINT [FK_EMP_GRP_ASS_EMP] FOREIGN KEY ([EMP_SK]) REFERENCES [dbo].[EMP] ([EMP_SK]),
    CONSTRAINT [FK_EMP_GRP_ASS_EMP_GRP_NODE] FOREIGN KEY ([EMP_GRP_NODE_SK]) REFERENCES [dbo].[EMP_GRP_NODE] ([EMP_GRP_NODE_SK])
);

