CREATE TABLE [dbo].[EMP_GRP_NODE] (
    [EMP_GRP_NODE_SK]  NUMERIC (15, 1) NOT NULL,
    [EMP_GRP_TREE_SK]  NUMERIC (15, 1) NOT NULL,
    [CODE]             NVARCHAR (30)   NOT NULL,
    [DESCR]            NVARCHAR (30)   NOT NULL,
    [LEFT_VISIT_NUM]   NUMERIC (15, 1) NOT NULL,
    [RIGHT_VISIT_NUM]  NUMERIC (15, 1) NOT NULL,
    [ALLOW_ASS_FLAG]   NCHAR (1)       NOT NULL,
    [ALLOW_LDR_FLAG]   NCHAR (1)       NOT NULL,
    [EMP_GRP_CLASS_SK] NUMERIC (15, 1) NULL,
    [UPD_TCS_LOGIN_SK] NUMERIC (15, 1) NOT NULL,
    [UPD_TS]           DATETIME        NOT NULL,
    CONSTRAINT [PKEMPGRPNODE] PRIMARY KEY CLUSTERED ([EMP_GRP_NODE_SK] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_EMP_GRP_NODE_EMP_GRP_CLASS] FOREIGN KEY ([EMP_GRP_CLASS_SK]) REFERENCES [dbo].[EMP_GRP_CLASS] ([EMP_GRP_CLASS_SK]),
    CONSTRAINT [FK_EMP_GRP_NODE_EMP_GRP_TREE] FOREIGN KEY ([EMP_GRP_TREE_SK]) REFERENCES [dbo].[EMP_GRP_TREE] ([EMP_GRP_TREE_SK])
);

