CREATE TABLE [dbo].[EMP_GRP_CLASS] (
    [EMP_GRP_CLASS_SK] NUMERIC (15, 1) NOT NULL,
    [LABEL]            NVARCHAR (30)   NOT NULL,
    [EMP_GRP_TREE_SK]  NUMERIC (15, 1) NOT NULL,
    CONSTRAINT [PKEMPGRPCLASS] PRIMARY KEY CLUSTERED ([EMP_GRP_CLASS_SK] ASC) WITH (FILLFACTOR = 75),
    CONSTRAINT [FK_EMP_GRP_CLASS_EMP_GRP_TREE] FOREIGN KEY ([EMP_GRP_TREE_SK]) REFERENCES [dbo].[EMP_GRP_TREE] ([EMP_GRP_TREE_SK])
);

