CREATE TABLE [dbo].[EMP_GRP_ASS_STG] (
    [EMP_GRP_NODE_SK] NUMERIC (15, 1) NULL,
    [EMP_GRP_ASS_SK]  NUMERIC (15, 1) NULL,
    [EMP_SK]          NUMERIC (15, 1) NULL,
    [START_NOM_DATE]  NUMERIC (15, 1) NULL,
    [STOP_NOM_DATE]   NUMERIC (15, 1) NULL,
    [LDR]             NVARCHAR (1)    NULL
);

