CREATE TABLE [dbo].[Emp_Grp] (
    [EMP_GRP_NODE_SK]  NUMERIC (15, 1) NOT NULL,
    [EMP_GRP_CLASS_SK] NUMERIC (15, 1) NULL,
    [CODE]             NVARCHAR (30)   NULL,
    CONSTRAINT [PK_Emp_Grp_1] PRIMARY KEY CLUSTERED ([EMP_GRP_NODE_SK] ASC)
);

