CREATE TABLE [dbo].[IDP_DSP_COL] (
    [IDP_DSP_COL_ID] NVARCHAR (30)   NOT NULL,
    [SEQ_NUM]        NUMERIC (15, 1) NOT NULL,
    [GRP_TYPE]       NCHAR (2)       NOT NULL,
    [DATA_TYPE]      NCHAR (1)       NOT NULL,
    [DEF_COL_RES_ID] NUMERIC (15, 1) NOT NULL,
    [DESCR_RES_ID]   NUMERIC (15, 1) NOT NULL,
    [COMBO_DSP_FLAG] NCHAR (1)       NOT NULL,
    [MAX_DEC_PRECS]  NUMERIC (15, 1) NULL,
    CONSTRAINT [PKIDPDSPCOL] PRIMARY KEY CLUSTERED ([IDP_DSP_COL_ID] ASC) WITH (FILLFACTOR = 90)
);

