CREATE TABLE [dbo].[OPEN_HRS] (
    [OPEN_HRS_SK]      NUMERIC (15, 1) NOT NULL,
    [CODE]             NVARCHAR (30)   NOT NULL,
    [DESCR]            NVARCHAR (30)   NOT NULL,
    [TIME_ZONE_SK]     NUMERIC (15, 1) NOT NULL,
    [MEMO]             NVARCHAR (MAX)  NULL,
    [UPD_TCS_LOGIN_SK] NUMERIC (15, 1) NOT NULL,
    [UPD_TS]           DATETIME        NOT NULL,
    CONSTRAINT [PKOPENHRS] PRIMARY KEY CLUSTERED ([OPEN_HRS_SK] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK1OPENHRS] FOREIGN KEY ([TIME_ZONE_SK]) REFERENCES [dbo].[TIME_ZONE] ([TIME_ZONE_SK]),
    CONSTRAINT [FK2OPENHRS] FOREIGN KEY ([UPD_TCS_LOGIN_SK]) REFERENCES [dbo].[TCS_LOGIN] ([TCS_LOGIN_SK])
);

