CREATE TABLE [dbo].[RTG_SET] (
    [RTG_SET_SK]        NUMERIC (15, 1) NOT NULL,
    [CODE]              NVARCHAR (30)   NOT NULL,
    [DESCR]             NVARCHAR (30)   NOT NULL,
    [SRVC_LEV_GOAL_SEC] NUMERIC (15, 1) NOT NULL,
    [UPD_TCS_LOGIN_SK]  NUMERIC (15, 1) NOT NULL,
    [UPD_TS]            DATETIME        NOT NULL,
    CONSTRAINT [PKRTGSET] PRIMARY KEY CLUSTERED ([RTG_SET_SK] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK2RTGSET] FOREIGN KEY ([UPD_TCS_LOGIN_SK]) REFERENCES [dbo].[TCS_LOGIN] ([TCS_LOGIN_SK])
);

