CREATE TABLE [dbo].[SECUR_PROF] (
    [SECUR_PROF_SK]    NUMERIC (15, 1) NOT NULL,
    [CODE]             NVARCHAR (30)   NOT NULL,
    [DESCR]            NVARCHAR (30)   NOT NULL,
    [UPD_TCS_LOGIN_SK] NUMERIC (15, 1) NOT NULL,
    [UPD_TS]           DATETIME        NOT NULL,
    CONSTRAINT [PKSECURPROF] PRIMARY KEY CLUSTERED ([SECUR_PROF_SK] ASC) WITH (FILLFACTOR = 90)
);

