CREATE TABLE [dbo].[SPRSTATE] (
    [SPRSTATE_SK]      NUMERIC (15, 1) NOT NULL,
    [CODE]             NVARCHAR (30)   NOT NULL,
    [DESCR]            NVARCHAR (30)   NOT NULL,
    [HRS_UPD_FLAG]     NCHAR (1)       NOT NULL,
    [UPD_TCS_LOGIN_SK] NUMERIC (15, 1) NOT NULL,
    [UPD_TS]           DATETIME        NOT NULL,
    CONSTRAINT [PKSPRSTATE] PRIMARY KEY CLUSTERED ([SPRSTATE_SK] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK1SPRSTATE] FOREIGN KEY ([UPD_TCS_LOGIN_SK]) REFERENCES [dbo].[TCS_LOGIN] ([TCS_LOGIN_SK])
);

