CREATE TABLE [dbo].[StaffPlan] (
    [ID]                       BIGINT         IDENTITY (1, 1) NOT NULL,
    [lobID]                    INT            NOT NULL,
    [siteID]                   INT            NOT NULL,
    [Week]                     DATE           NOT NULL,
    [Planned Attrition]        NUMERIC (5, 4) NULL,
    [Planned Occupancy]        NUMERIC (5, 4) NULL,
    [Planned Shrinkage]        NUMERIC (5, 4) NULL,
    [Planned OOC Shrinkage]    NUMERIC (5, 4) NULL,
    [Planned ABS]              NUMERIC (5, 4) NULL,
    [Planned PTO]              NUMERIC (5, 4) NULL,
    [Planned LOA]              NUMERIC (5, 4) NULL,
    [Planned IC Shrinkage]     NUMERIC (5, 4) NULL,
    [Planned Break]            NUMERIC (5, 4) NULL,
    [Planned Coach]            NUMERIC (5, 4) NULL,
    [Planned Lead]             NUMERIC (5, 4) NULL,
    [Planned Meeting]          NUMERIC (5, 4) NULL,
    [Planned Personal]         NUMERIC (5, 4) NULL,
    [Planned Preshift]         NUMERIC (5, 4) NULL,
    [Planned Project]          NUMERIC (5, 4) NULL,
    [Planned System]           NUMERIC (5, 4) NULL,
    [Planned Training]         NUMERIC (5, 4) NULL,
    [Planned Unaccounted Time] NUMERIC (5, 4) NULL,
    [Planned HC]               NUMERIC (9, 2) NULL,
    [Tenured HC Adj.]          NUMERIC (9, 2) NULL,
    [Tenured HC]               NUMERIC (9, 2) NULL,
    [Non-Tenured HC]           NUMERIC (9, 2) NULL,
    [Nesting HC]               NUMERIC (9, 2) NULL,
    [Training HC]              NUMERIC (9, 2) NULL,
    [Planned Hours]            NUMERIC (9, 2) NULL,
    [Tenured Hours]            NUMERIC (9, 2) NULL,
    [Non-Tenured Hours]        NUMERIC (9, 2) NULL,
    [Nesting Hours]            NUMERIC (9, 2) NULL,
    [Training Hours]           NUMERIC (9, 2) NULL,
    [Planned AHT]              NUMERIC (9, 2) NULL,
    [Tenured AHT]              NUMERIC (9, 2) NULL,
    [Non-Tenured AHT]          NUMERIC (9, 2) NULL,
    [Nesting AHT]              NUMERIC (9, 2) NULL,
    [Training AHT]             NUMERIC (9, 2) NULL,
    [Planned Concurrency]      NUMERIC (9, 2) NULL,
    [Tenured Concurrency]      NUMERIC (9, 2) NULL,
    [Non-Tenured Concurrency]  NUMERIC (9, 2) NULL,
    [Nesting Concurrency]      NUMERIC (9, 2) NULL,
    [Training Concurrency]     NUMERIC (9, 2) NULL,
    [Planned FTE]              NUMERIC (9, 2) NULL,
    [Tenured FTE]              NUMERIC (9, 2) NULL,
    [Non-Tenured FTE]          NUMERIC (9, 2) NULL,
    [Nesting FTE]              NUMERIC (9, 2) NULL,
    [Training FTE]             NUMERIC (9, 2) NULL,
    [Planned Capacity]         NUMERIC (9, 2) NULL,
    [Capacity Adj.]            NUMERIC (9, 2) NULL,
    [Tenured Capacity]         NUMERIC (9, 2) NULL,
    [Non-Tenured Capacity]     NUMERIC (9, 2) NULL,
    [Nesting Capacity]         NUMERIC (9, 2) NULL,
    [Training Capacity]        NUMERIC (9, 2) NULL,
    [Production Seats]         NUMERIC (9, 2) NULL,
    [Training Seats]           NUMERIC (9, 2) NULL,
    CONSTRAINT [PK_StaffPlan] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SP_LOB] FOREIGN KEY ([lobID]) REFERENCES [dbo].[LOB] ([ID]),
    CONSTRAINT [FK_StaffPlan_Site] FOREIGN KEY ([siteID]) REFERENCES [dbo].[Site] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_StaffPlan]
    ON [dbo].[StaffPlan]([lobID] ASC, [siteID] ASC, [Week] ASC);

