CREATE TABLE [dbo].[STF_GRP_TREE] (
    [STF_GRP_TREE_SK] NUMERIC (15, 1) NOT NULL,
    [STATE_SK]        NUMERIC (15, 1) NOT NULL,
    CONSTRAINT [PKSTFGRPTREE] PRIMARY KEY CLUSTERED ([STF_GRP_TREE_SK] ASC) WITH (FILLFACTOR = 90)
);

