CREATE TABLE [dbo].[THD_SET] (
    [THD_SET_SK]         NUMERIC (15, 1) NOT NULL,
    [CODE]               NVARCHAR (30)   NOT NULL,
    [DESCR]              NVARCHAR (30)   NOT NULL,
    [LWR_BND_COLOR]      NUMERIC (15, 1) NOT NULL,
    [LWR_BND_FONT_COLOR] NUMERIC (15, 1) NOT NULL,
    [UPR_BND_COLOR]      NUMERIC (15, 1) NOT NULL,
    [UPR_BND_FONT_COLOR] NUMERIC (15, 1) NOT NULL,
    [CRE_TCS_LOGIN_SK]   NUMERIC (15, 1) NOT NULL,
    [CRE_TS]             DATETIME        NOT NULL,
    [UPD_TCS_LOGIN_SK]   NUMERIC (15, 1) NOT NULL,
    [UPD_TS]             DATETIME        NOT NULL,
    CONSTRAINT [PKTHDSET] PRIMARY KEY CLUSTERED ([THD_SET_SK] ASC) WITH (FILLFACTOR = 90)
);

