CREATE TABLE [dbo].[TIME_ZONE] (
    [TIME_ZONE_SK]       NUMERIC (15, 1) NOT NULL,
    [RES_ID]             NUMERIC (15, 1) NOT NULL,
    [ZONE_NAME]          NVARCHAR (60)   NOT NULL,
    [MEMO]               NVARCHAR (MAX)  NULL,
    [XCHNG_TIME_ZONE_SK] NUMERIC (15, 1) NULL,
    CONSTRAINT [PKTIMEZONE] PRIMARY KEY CLUSTERED ([TIME_ZONE_SK] ASC) WITH (FILLFACTOR = 90)
);

