CREATE TABLE [dbo].[WFM_Metrics_HAgent] (
    [i_availtime]    FLOAT (53)    NULL,
    [row_date]       DATE          NOT NULL,
    [starttime]      SMALLINT      NOT NULL,
    [acd]            INT           NOT NULL,
    [Vendor_ID]      INT           NOT NULL,
    [logid]          VARCHAR (15)  NOT NULL,
    [LOB_ID]         INT           NOT NULL,
    [i_acdtime]      BIGINT        NULL,
    [i_acwtime]      BIGINT        NULL,
    [i_acwintime]    BIGINT        NULL,
    [i_acwouttime]   BIGINT        NULL,
    [i_auxintime]    BIGINT        NULL,
    [i_auxouttime]   BIGINT        NULL,
    [i_acdothertime] BIGINT        NULL,
    [acdcalls]       BIGINT        NULL,
    [ti_auxtime0]    BIGINT        NULL,
    [Break]          BIGINT        NULL,
    [Meeting]        BIGINT        NULL,
    [Lunch]          BIGINT        NULL,
    [Lead]           BIGINT        NULL,
    [Closed]         BIGINT        NULL,
    [DCTR]           BIGINT        NULL,
    [Coach_Meeting]  BIGINT        NULL,
    [Train]          BIGINT        NULL,
    [Project]        BIGINT        NULL,
    [Computer]       BIGINT        NULL,
    [Personal]       BIGINT        NULL,
    [Union]          BIGINT        NULL,
    [Outbound]       BIGINT        NULL,
    [Mentoring]      BIGINT        NULL,
    [Aux]            BIGINT        NULL,
    [EOS]            BIGINT        NULL,
    [Chat]           BIGINT        NULL,
    [PCBootup]       BIGINT        NULL,
    [Site]           NVARCHAR (30) NOT NULL,
    CONSTRAINT [PK_WFM_Metrics_HAgent] PRIMARY KEY CLUSTERED ([row_date] ASC, [starttime] ASC, [acd] ASC, [Vendor_ID] ASC, [logid] ASC, [LOB_ID] ASC, [Site] ASC)
);

